In [5]:
### NumPy
# 고성능 수치 계산을 위해서 제작된 파이썬 라이브러리
# 머신러닝 또는 딥러닝 알고리즘은 기본적으로 다차원 배열에 대한 계산으로 볼 수 있음
# 또는 대량 데이터를 다룰 때에 빠른 계산 능력이 요구되어 사용되는 라이브러리

# 생성된 NumPy 확인 - NumPy의 핵심객체(Ndarray)
import numpy as np

temp = np.array([1,2,3])
print(type(temp))

## 토튜리얼 : https://numpy.org/doc/stable/user/quickstart.html

# NumPy 기본 문법

# - list
data1 = [1,2,3]
data1

data2 = [1,1,2,2,3,4]
data2

# np.array으로 배열로 변환
my_array1 = np.array(data1)
print(my_array1)
print(my_array1.shape)

my_array2 = np.array(data2)
print(my_array2)
print(my_array2.shape)

# shape는 크기를 확인하는 함수

## 리스트 선언 없이 바로 배열로 사용
my_array3 = np.array([3,4,5,7])
print(my_array3.dtype)

## Data types 참조 : https://numpy.org/devdocs/user/basics.types.html

<class 'numpy.ndarray'>
[1 2 3]
(3,)
[1 1 2 2 3 4]
(6,)
int32


In [6]:
### 2차 배열
my_array4 = np.array([[2,4,6],[8,10,12],[14,16,18],[20,22,24]])
my_array4
my_array4.shape

(4, 3)

In [11]:
### 3차 배열
my_array5 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
my_array5
my_array5.shape

(2, 2, 2)

In [15]:
### NumPy 배열 생성 및 둘러보기
# Arrange : 기본 함수 중에 Range함수와 조금 유사하며, 더욱 쉽게 배열을 만들게 함
arrage_array = np.arange(5)
arrage_array

arrage_array2 = np.arange(1, 9)
print(arrage_array2)
arrage_array2.dtype

[1 2 3 4 5 6 7 8]


dtype('int32')

In [16]:
### Zeros, Ones
# 할당하는 사이즈 배열에 0이나 1을 더욱 쉽게 입력하는 함수
zeros_arr = np.zeros((3,2))
print(zeros_arr)
print("Data Type is : ", zeros_arr.dtype)
print("Data Shape is : ", zeros_arr.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
Data Type is :  float64
Data Shape is :  (3, 2)


In [18]:
ones_arr = np.ones((3,4))
print(ones_arr)
print("Data Type is : ", ones_arr.dtype)
print("Data Shape is : ", ones_arr.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Data Type is :  float64
Data Shape is :  (3, 4)


In [32]:
## Reshape
after_reshape = ones_arr.reshape(6,2)
print(after_reshape)
print("Data Shape is : ", after_reshape.shape)

## 항상 변경이 가능하지는 않다. 조건은 Size가 동일해야 한다
# ones_arr를 다른 사이즈 변경해보세요. 3가지 정도
after_reshape1=ones_arr.reshape(2,3,2)
print(after_reshape1)
print("-"*20)
after_reshape2=ones_arr.reshape(3,2,2)
print(after_reshape2)
print("-"*20)
after_reshape3=ones_arr.reshape(2,2,3)
print(after_reshape3)
print("-"*20)

### reshape()에서 -1의 의미는? 차원을 자동으로 계산한다는 의미
after_reshape4 = ones_arr.reshape(-1,1)
print(after_reshape4)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Data Shape is :  (6, 2)
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [37]:
### NumPy 인덱싱과 슬라이싱
my_array = np.arange(0, 4)
print(my_array)

print("my_array의 1번째 요소, 즉 0번인 것은 : ",my_array[0])
print("my_array[0:3] : ",my_array[0:3])
print("my_array[0:3] : ",my_array[0:])
print("my_array[0:3] : ",my_array[:2])
print("my_array[0:3] : ",my_array[:])
print("my_array[0:3] : ",my_array[0:-1])

[0 1 2 3]
my_array의 1번째 요소, 즉 0번인 것은 :  0
my_array[0:3] :  [0 1 2]
my_array[0:3] :  [0 1 2 3]
my_array[0:3] :  [0 1]
my_array[0:3] :  [0 1 2 3]
my_array[0:3] :  [0 1 2]


In [42]:
my_array2 = np.array(
    [[2,4,6,8,10,12,14,16,18],
     [3,6,9,12,15,18,21,24,27],
     [4,8,12,16,20,24,28,32,36],
     [5,10,15,20,25,30,35,40,45]]
)
print(my_array2)
print(my_array2.shape)
print(my_array2[0:2, 0:2])
print(my_array2[1:3, :])

[[ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]]
(4, 9)
[[2 4]
 [3 6]]
[[ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]]


In [45]:
### NumPy정렬 : sort(), argsort()

# np.sort() : 원본에 변화를 주지 않고 복사본을 전달함
height_arr = np.array([174, 165, 182, 180, 168])
sorted_height_arr = np.sort(height_arr)
print("Height Matrix : ", height_arr)
print("np.sort() Matrix : ", sorted_height_arr)

# 내림차순 정렬
desc_sorted_height_arr = np.sort(height_arr)[::-1]
print("np.sort()[::-1] : ", desc_sorted_height_arr)

Height Matrix :  [174 165 182 180 168]
np.sort() Matrix :  [165 168 174 180 182]
np.sort()[::-1] :  [182 180 174 168 165]


In [47]:
### argsort()
# numpy.argsort() 함수는 지정된 축을 따라 데이터 인덱스의 배열을 반환하도록
# 지정된 종류의 정렬을 사용해 입력 배열에서 간접 정렬을 수행함

fives = np.array([10,5,15,20])
fives_order = fives.argsort()

print("original data : ", fives)
print("argsort() : ", fives_order)
print("Ascending : ", fives[fives_order])

# NumPyTutorials: https://numpy.org/learn/
# NumPy Broadacsting: https://numpy.org/doc/stable/user/basics.broadcasting.html
# 숙제. 같은 크기의 두 배열에 대한 연산과 서로 크기가 다른 두 배열의 연산을 공부하세요

original data :  [10  5 15 20]
argsort() :  [1 0 2 3]
Ascending :  [ 5 10 15 20]


In [4]:
## 판다스 .. 연습
## sample.xlsx 데이터 불러오기

import pandas as pd
excel=pd.read_excel('data/sample_1.xlsx',
                    header=1,
                    skipfooter=2,
                    usecols='A:C')
excel.head(3)       #상위 5개 출력

국적코드  성별    입국객수
0  A01  남성  106320
1  A01  여성  191436
2  A31  남성     319

In [5]:
## 하위 5개 출력 : tail()
excel.tail()

국적코드  성별    입국객수
1  A01  여성  191436
2  A31  남성     319
3  A31  여성      42
4  A18  남성  158912
5  A18  여성  232943

In [6]:
## 데이터 정보 보기 : info()
excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   국적코드    6 non-null      object
 1   성별      6 non-null      object
 2   입국객수    6 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 272.0+ bytes


In [7]:
## sample_1의 데이터 기초 통계량 확인 :describe()
excel.describe()


입국객수
count       6.000000
mean   114995.333333
std     98105.752006
min        42.000000
25%     26819.250000
50%    132616.000000
75%    183305.000000
max    232943.000000

In [12]:
## 연습.. 각 컬럼별 시리즈를 확인하세요
# [입국객수],[국적코드, 입국객수],[국적코드,성별]
excel
print(excel['입국객수'],type(excel['입국객수']))
print(excel[['국적코드','입국객수']],type(excel[['국적코드','입국객수']]))


0    106320
1    191436
2       319
3        42
4    158912
5    232943
Name: 입국객수, dtype: int64 <class 'pandas.core.series.Series'>
  국적코드    입국객수
0  A01  106320
1  A01  191436
2  A31     319
3  A31      42
4  A18  158912
5  A18  232943 <class 'pandas.core.frame.DataFrame'>


In [14]:
## df에 컬럼 생성 "기준년월" : 2019-11
excel['기준년월']='2019-11'
excel

국적코드  성별    입국객수     기준년월
0  A01  남성  106320  2019-11
1  A01  여성  191436  2019-11
2  A31  남성     319  2019-11
3  A31  여성      42  2019-11
4  A18  남성  158912  2019-11
5  A18  여성  232943  2019-11

In [18]:
## 필터링하기...
# 1. 성별이 남성인 데이터 출력
condition=(excel['성별']=='남성')
excel[condition]
# 2. 입국객수 15000 미만 출력
condition=(excel['입국객수']<15000)
excel[condition]
# 3. 성별이 남성이면서 150000만 이상
condition=(excel['성별']=='남성')&(excel['입국객수']>150000)
excel[condition]


국적코드  성별    입국객수     기준년월
4  A18  남성  158912  2019-11

In [21]:
## 4. 한 컬럼(시리즈)에서 여러조건 필터링
# 국적 코드가 "A01","A18"인 경우만 출력

condition=(excel['국적코드']=='A01')|(excel['국적코드']=='A18')
condition=(excel['국적코드'].isin(['A01','A18']))

# 조건 제외 선택
excel[condition==False]


국적코드  성별  입국객수     기준년월
2  A31  남성   319  2019-11
3  A31  여성    42  2019-11

In [23]:
## 데이터 합치기
# sample_codemaster.xlsx 파일을 code_master(DF)로 불러오기

import pandas as pd
codemaster=pd.read_excel('data/sample_codemaster.xlsx')
codemaster

국적코드     국적명
0  A01      일본
1  A02      대만
2  A03      홍콩
3  A18      중국
4  A19      이란
5  A22  우즈베키스탄
6  A23   카자흐스탄
7  A99  아시아 기타

In [37]:
# 옆으로 통합하기
sample_1_code=pd.merge(left=excel,right=codemaster,how='left',# how left/right - 기준으로 표시
                        left_on='국적코드',right_on='국적코드')        
sample_1_code

국적코드  성별    입국객수     기준년월  국적명
0  A01  남성  106320  2019-11   일본
1  A01  여성  191436  2019-11   일본
2  A31  남성     319  2019-11  NaN
3  A31  여성      42  2019-11  NaN
4  A18  남성  158912  2019-11   중국
5  A18  여성  232943  2019-11   중국

In [43]:
## 데이터 통합(아래)
# -> sample_2 라는 df를 만드세요 sample_2.xlsx 사용
# 국적 코드, 성별, 입국객수만 출력, 불필요 데이터 제거
# 추가로 기준년월 :2019-12 추가
sample_2=pd.read_excel('data/sample_2.xlsx', header=1,skipfooter=2,usecols='A:C')
sample_2['기준년월']='2019-12'
sample_2

sample=sample_1_code.append(sample_2,ignore_index=True)
sample


C:\Users\djagk\AppData\Local\Temp\ipykernel_5128\3479199419.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sample=sample_1_code.append(sample_2,ignore_index=True)


국적코드  성별    입국객수     기준년월  국적명
0  A01  남성  106320  2019-11   일본
1  A01  여성  191436  2019-11   일본
2  A31  남성     319  2019-11  NaN
3  A31  여성      42  2019-11  NaN
4  A18  남성  158912  2019-11   중국
5  A18  여성  232943  2019-11   중국
6  A01  남성   92556  2019-12  NaN
7  A01  여성  163737  2019-12  NaN
8  A18  남성  155540  2019-12  NaN
9  A18  여성  249023  2019-12  NaN

In [44]:
## pandas 사용하여 병합하기
sample2=pd.concat([sample_1_code,sample_2],ignore_index=True)
sample2

국적코드  성별    입국객수     기준년월  국적명
0  A01  남성  106320  2019-11   일본
1  A01  여성  191436  2019-11   일본
2  A31  남성     319  2019-11  NaN
3  A31  여성      42  2019-11  NaN
4  A18  남성  158912  2019-11   중국
5  A18  여성  232943  2019-11   중국
6  A01  남성   92556  2019-12  NaN
7  A01  여성  163737  2019-12  NaN
8  A18  남성  155540  2019-12  NaN
9  A18  여성  249023  2019-12  NaN

In [45]:
# 위 sample을 뎅이터 엑셀파일로 저장
sample.to_excel('data/sample.xlsx')

In [46]:
# 인덱스값 제거하여 저장
sample2.to_excel('data/sample2.xlsx',index=False)

In [49]:
# 데이터 집계하기 (pivot_table)
#pivot_table() 함수 활용
sample_pivot=sample.pivot_table(values='입국객수',index='국적명',columns='기준년월',aggfunc='mean')
sample_pivot

기준년월   2019-11
국적명           
일본    148878.0
중국    195927.5

In [50]:
sample_pivot_2=sample.pivot_table(values='입국객수',index='국적명',aggfunc='max')
sample_pivot_2

입국객수
국적명        
일본   191436
중국   232943

In [51]:
sample_pivot_3=sample.pivot_table(values='입국객수',index='국적명',aggfunc='min')
sample_pivot_3

입국객수
국적명        
일본   106320
중국   158912

In [53]:
sample_pivot_4=sample.pivot_table(values='입국객수',index='국적명',columns='기준년월',aggfunc='sum')
sample_pivot_4

기준년월  2019-11
국적명          
일본     297756
중국     391855